[package]
name = "swift_archiver"
version = "0.1.0"
authors = ["Rob Porter <rob@inpictures.ca>"]
edition = "2018"

[dependencies]
toml = "0.5.1"
serde_derive = "1.0.92"
serde = "1"
curl = "0.4.22"
colored = "1.8.0"